### ISSUE TITLE
Screen static

### ISSUE THREAD

**Issue by iYlizzz** [absolllute/Mega-Hack-Pro-Future#1095]
Hey whenever I'm playing a level, could be bloodbath, stereo madness etc... I get an annoying static in the middle of the screen. Uninstalled gd, played it without the megahack and the static disappeared. So, I don't know if its a megahack error or mine.

**Comment by MainConMan** [comment]
if possible, can you send a screen recording of this?

**Comment by NewAlexGamer** [comment]
i don't really know what you mean by static but i presume it's screen tearing. this is where it splits somewhere in the screen for what you'd say no apparent reason. that's because the fps of your game isn't synced up with the refresh rate of your monitor. enable vsync in the settings to fix that (or use bypass it still works for me)

**Comment by MainConMan** [comment]
> i don't really know what you mean by static but i presume it's screen tearing. 

Yeah this is what i was thinkin, but i wasnt sure, so asked for a video

**Comment by absoIute** [comment]
most likely screen tearing, not followed up
