### ISSUE TITLE
Crash Trigger Detection / Remover

### ISSUE THREAD

**Issue by yoghurtbang** [absolllute/Mega-Hack-Pro-Future#171]
I was wondering if a future feature either of v6 / v7 could be either something that detects Crash Tiggers.

As someone who bots / showcases levels - I've recently experienced multiple crash triggers either in worked-on levels or troll levels in general.
I was wondering if either some sort of detection or alternatively toggling off the trigger to prevent it from activating aka crashing the game causing a restart and all progress before the last save to be lost. 

Again, as I am not a developer , I'm not sure how information is stored or how it can be manipulated - but I think if possible the option would be beneficial to a growing number of users, thought it was interesting to think about the possibility.

**Comment by Brittank88** [comment]
I think this would be a fantastic feature in relation to general data safety in GD.

You could probably detect triggers like these by enforcing upper/lower bounds for values. Maybe less invasively, injecting some code to catch out-of-bounds exceptions caused by such triggers would render them useless without actually involving any changes to trigger values themselves.

**Comment by absoIute** [comment]
Looking into it, I know a few common instances of crash triggers, but if there are others feel free to dump levelIDs here so I can take a look!

**Comment by absoIute** [comment]
Implemented in v7.1-beta4
