### ISSUE TITLE
MegaHack v7 Appearing Logged Out On Manjaro

### ISSUE THREAD

**Issue by NoelleTGS** [absolllute/Mega-Hack-Pro-Future#732]
I followed @/Kho-Dialga's tutortial to get MHv7 running on Linux and it seems to have installed fine, but when I launch GD it tells me I'm not logged in and won't let me use the program. I know Linux isn't officially supported but I figured I'd ask here anyway. I've tried doing the process all over again but I get the same result. Is there any file in the directory where I can manually input my login, or any other solution like that?

**Comment by Brittank88** [comment]
I doubt that there exists a file to store your credentials as the form on the GUI probably just directly takes your input and sends it to the server before doing everything else it does.

It'll be up to Absolute to explain how the application actually checks that you're logged in though.

**Comment by absoIute** [comment]
You need to run the installer under the same instance of Proton/Wine as GD since it downloads your license from the server and is bound to your device, easiest way to do this is to:
- drag the v7 installer files into GD's installer folder
- swap MegaHackInstaller.exe's & GeometryDash.exe's names
- run Geometry Dash from Steam
- logout all -> login -> install
- then close the installer and swap the files back
