### ISSUE TITLE
Zoom Out Option

### ISSUE THREAD

**Issue by Unspeakable-Boy** [absolllute/Mega-Hack-Pro-Future#957]
Just like infinite zoom in, how about out too? That would be kind of helpful.

**Comment by NewAlexGamer** [comment]
it was doable before, but got removed because after you zoomed twice farther than this it would crash your game. i believe the first zoom was just the editor grid and the level vanishing, the second was the crash
![image](https://user-images.githubusercontent.com/86263500/185279640-a4ecdd1f-dc36-4c67-8305-967334790a67.png)
